# Generated by Django 2.0.2 on 2018-11-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('job_category', models.CharField(blank=True, max_length=255, null=True)),
                ('job_name', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_time', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('job_info', models.CharField(blank=True, max_length=5000, null=True)),
                ('request_num', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=800, null=True)),
                ('company_scale', models.CharField(blank=True, max_length=255, null=True)),
                ('company_net', models.CharField(blank=True, max_length=255, null=True)),
                ('company_property', models.CharField(blank=True, max_length=255, null=True)),
                ('company_business', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_time', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'recruit_info',
            },
        ),
        migrations.CreateModel(
            name='RecruitInfoMyTest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_time', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('job_info', models.CharField(blank=True, max_length=1000, null=True)),
                ('job_require', models.CharField(blank=True, max_length=1000, null=True)),
                ('request_num', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('company_scale', models.CharField(blank=True, max_length=255, null=True)),
                ('company_net', models.CharField(blank=True, max_length=255, null=True)),
                ('company_property', models.CharField(blank=True, max_length=255, null=True)),
                ('company_business', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_time', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'recruit_info_my_test',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('ip', models.CharField(max_length=255)),
                ('index', models.IntegerField()),
                ('ip_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
